apiVersion: v1
kind: Service

metadata:
  name: deployment-platform-service

spec:
  type: NodePort

  selector:
    app: deployment-platform

  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30008